name: my_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: 2.4.4
  animated_splash_screen: ^1.3.0

flutter_native_splash:
  color: "#ffffff" # White background (ensure it's a valid hex color)
  image: assets/images/logo.png # Make sure this image exists
  color_dark: "#000000" # Dark mode background
  image_dark: assets/images/logo.png # Ensure this image path is correct
  android_12:
    color: "#ffffff"
    color_dark: "#000000"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/Cart.png
    - assets/images/check_mark.png
    - assets/images/shoe_1.png
    - assets/images/shoe_2.png
    - assets/images/logo.png
    - assets/animation/splash_1.gif
