// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCEaPwtz72crbfSRQnH0LaUep1q7MH_pg',
    appId: '1:782470208680:web:38d9955604f70d24a5369d',
    messagingSenderId: '782470208680',
    projectId: 'appauthentication-5b063',
    authDomain: 'appauthentication-5b063.firebaseapp.com',
    storageBucket: 'appauthentication-5b063.firebasestorage.app',
    measurementId: 'G-VECJ7GW091',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqBAA40iHRFNXSvqoCNhfIQelRvu_c8Bc',
    appId: '1:782470208680:android:e4fa017c2d76bad5a5369d',
    messagingSenderId: '782470208680',
    projectId: 'appauthentication-5b063',
    storageBucket: 'appauthentication-5b063.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx3YnXjTeOXPoenHIWf0UdoSuBU0kM9Xc',
    appId: '1:782470208680:ios:bbcd391e64bd8c6fa5369d',
    messagingSenderId: '782470208680',
    projectId: 'appauthentication-5b063',
    storageBucket: 'appauthentication-5b063.firebasestorage.app',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx3YnXjTeOXPoenHIWf0UdoSuBU0kM9Xc',
    appId: '1:782470208680:ios:bbcd391e64bd8c6fa5369d',
    messagingSenderId: '782470208680',
    projectId: 'appauthentication-5b063',
    storageBucket: 'appauthentication-5b063.firebasestorage.app',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCEaPwtz72crbfSRQnH0LaUep1q7MH_pg',
    appId: '1:782470208680:web:6ba2bc6d2997079da5369d',
    messagingSenderId: '782470208680',
    projectId: 'appauthentication-5b063',
    authDomain: 'appauthentication-5b063.firebaseapp.com',
    storageBucket: 'appauthentication-5b063.firebasestorage.app',
    measurementId: 'G-1XG6FS7Z5L',
  );
}
