// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6fjDqiJ0iGIQCYoPeWXC4ZkwSSuz0bIA',
    appId: '1:1010877329943:web:1e194814e6e63180e6e252',
    messagingSenderId: '1010877329943',
    projectId: 'cerdentials',
    authDomain: 'cerdentials.firebaseapp.com',
    storageBucket: 'cerdentials.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhNnGeqsTQodx8wfEPzg3MPD-6v_7tt4A',
    appId: '1:1010877329943:android:27e9f11f8d3b5679e6e252',
    messagingSenderId: '1010877329943',
    projectId: 'cerdentials',
    storageBucket: 'cerdentials.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6fjDqiJ0iGIQCYoPeWXC4ZkwSSuz0bIA',
    appId: '1:1010877329943:web:afd480f51932e879e6e252',
    messagingSenderId: '1010877329943',
    projectId: 'cerdentials',
    authDomain: 'cerdentials.firebaseapp.com',
    storageBucket: 'cerdentials.firebasestorage.app',
  );
}
